name: generate-gh-pages
run-name: Generate gh-pages / ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - docs-stable
  workflow_dispatch:

permissions: write-all

jobs:
  generate:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: docs-stable

    - name: Checkout changelog
      uses: actions/checkout@v5
      with:
        ref: docs-changelog
        path: docs/_changelog

    - name: Build BenchmarkDotNet
      run: ./build.cmd build

    - name: Fetch changelog
      run: ./build.cmd docs-fetch --depth 1 --preview
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build documentation
      run: ./build.cmd docs-build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: docs/_site

  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [generate]
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: docs-stable

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: site
        path: site

    - name: Print file tree
      run: tree $GITHUB_WORKSPACE

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: site
        git-config-name: Andrey Akinshin
        git-config-email: andrey.akinshin@gmail.com
        clean: true